/*
 * Geolocation API
 *
 * This is a Geolocation API
 *
 * API version: 1.0.0
 * Contact: dev@rakuten.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package domain

import (
	"time"

	"github.com/danilovalente/geolocationexample/repository"
)

/*
TransportRepository defines the repository capabilities that should be found in a Repository implementation for Transport
*/
type TransportRepository interface {
	repository.Repository
	Get(id string) (*Transport, error)
	GetAll() ([]*Transport, error)
	Save(transport *Transport) (string, error)
	UpdatePosition(transportID string, newPosition *Position) (*Transport, error)
}

//Transport represents a Transport object
type Transport struct {
	ID string `bson:"_id" json:"id"`

	Description string `bson:"description" json:"description"`

	Category string `bson:"category" json:"category,omitempty"`

	LastPositionReportedAt time.Time `bson:"lastPositionReportedAt" json:"lastPositionReportedAt,omitempty"`

	CurrentPosition *Position `bson:"currentPosition" json:"currentPosition"`
}
